version: '3.4'

services:
  web:
    image: ngser/contraventions-ussd:latest
    container_name: contraventions-ussd
    build: .
    depends_on:  
      - database
      - contraventions-redis
    ports:
      - "8570:3000"
    volumes:
      - .:/home/ngser/app
    env_file:
      - .env
    environment:
      - DB_USERNAME=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
  database:
    image: postgres:13.2-alpine
    restart: always
    ports: 
      - "5432"
    volumes:
      - "${DB_DATA_CONTRAVENTIONS_USSD}:/var/lib/postgresql/data"
    environment:
      # Setting postgresql credentials
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=contravention_ussd_db
  contraventions-redis:
    image: redis:6.2.1-alpine
    restart: always